# Choice of environment
env_mode: "basic"

# Max number of threads
max_threads: 4

# Range of kmer use
kmer_size:
  begin: 13
  end: 19
  step: 2

# Filter reads with solid kmer ratio lower than this range of ratio
kmrf_ratio:
  begin: 70
  end: 100
  step: 5

# Filter reads with quality lower than this range of quality
filtlong_quality:
  begin: 88
  end: 100
  step: 2

# Associate reads with correct reference
reads2ref:
  k12_mg1655: "k12_mg1655"
  s_cerevisiae_imx2538_nanopore: "s_cerevisiae_s288c"
  s_cerevisiae_imx2538_illumina: "s_cerevisiae_s288c"
  zymo_nanopore: "zymo"
  zymo_pacbio: "zymo"
  zymo_illumina: "zymo"

# Associate reference with genome size
ref2size:
  zymo: 41884608
  s_cerevisiae_s288c: 12157105
  k12_mg1655: :4641652

# counter enabled with extension
counter: [["pcon", "pcon"], ["kmc", "kmc_suf"], ["jellyfish", "jf"]]
